### PR TITLE
The Big Code Rework™

### PR DESCRIPTION
**Pull request by aprzn123**
Draft PR that we can merge once we've made all the rework changes

### CODE REVIEW

**Comment by HumanoidSandvichDispenser** [comment]
Current progress? What's left to do now?

**Comment by aprzn123** [comment]
Main things, I think, are improving config stuff and reducing code duplication between `third` and `fourth`

**Comment by aprzn123** [comment]
ok I'm going to do a code review on this and then merge it. might not be perfect, but i want this merged so i can start working on Actual Features again

**Comment by aprzn123** [comment]
First note is that before merging I should *definitely* write some docs on how to add a new feature

**Comment by aprzn123** [comment]
This might be about ready now! Perhaps someone should read over the docs, see if it's comprehensible enough lol

**Pull request merged**
