### PR TITLE
feature: avatar stealer button

### LINKED ISSUE #42: Feature: Avatar Stealer
A button that creates a new avatar based on another avatar

### PR DESCRIPTION
**Pull request by HumanoidSandvichDispenser**
resolves #42

image

### CODE REVIEW

**Review by aprzn123 — CHANGES_REQUESTED** [review]
Pretty good feature so far, but still needs to be toggleable in the popup menu-- see step 1 of docs/adding_features.md

**Comment by aprzn123** [comment]
Also-- do we need an injected script for this? I suspect you would be able to do it fine from `src/js/users.js` without having to inject into the page (something we're looking to avoid whenever possible)

**Comment by HumanoidSandvichDispenser** [comment]
Yeah otherwise it won't let me read the avatar image.

**Review by aprzn123 — APPROVED** [review]
looks good now :+1:

**Pull request merged**
