### PR TITLE
Use correct size measurement for avatars

### PR DESCRIPTION
**Pull request by thekifake**
So 32px was incorrect. 24px looks a lot more correct but if it used a specific value in a different measurement (i.e. `em`) then point that out and I'll update it. For the time being I'm 99% sure this is how it looked before.

### CODE REVIEW

**Review by HumanoidSandvichDispenser — APPROVED** [review]

**Comment by HumanoidSandvichDispenser** [comment]
The actual size was 16px

**Review by HumanoidSandvichDispenser — CHANGES_REQUESTED** [review]
The actual size was 16px

**Comment by thekifake** [comment]
Are you 100% sure? I don't remember it looking *that* small.

**Comment by thekifake** [comment]
I'll assume you're right and correct the entire thing. Thanks for the archive link.

**Comment by thekifake** [comment]
Okay, done. This should look a lot closer to how it originally was.

**Review by HumanoidSandvichDispenser — APPROVED** [review]

**Pull request merged**
